-- ============================================================================
--  ⚠  REINICIAR LA BASE — BORRA TODO
-- ----------------------------------------------------------------------------
--  Esto elimina TODAS las tablas, datos y políticas de ZUUUM FIBRA.
--  No hay deshacer.
--
--  Úsalo solo si algo salió mal a media instalación y quieres empezar limpio.
--  NUNCA en la base que ya trae los clientes de verdad.
--
--  Tus cuentas de Authentication NO se tocan: viven en el esquema `auth`,
--  que este archivo ni menciona.
-- ============================================================================
--
--  Para usarlo: quita los tres guiones dobles de las últimas tres líneas
--  y pégalo en el SQL Editor. Mientras estén comentadas, no hace nada.
--
-- ============================================================================

-- drop schema public cascade;
-- create schema public;
-- grant usage on schema public to anon, authenticated, service_role;
